import time, utilities, os, math
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.

def generate_nth_pentagonal_number(n):
    return n*(3*n-1)/2

def is_pentagonal(k):
    n = (1+math.sqrt(1+24*k))/6
    if generate_nth_pentagonal_number(n) == int(k) and n.is_integer():
        return True
    return False

if __name__ == '__main__':
    problem_number_str = utilities.get_problem_number(os.path.basename(__file__))

    print('Start working on Project Euler Problem: ' + problem_number_str)
    start_time = time.time()


    i = 3
    while True:

        p_i = generate_nth_pentagonal_number(i)
        print(i, p_i)
        for j in range(1,i):
            p_j = generate_nth_pentagonal_number(j)

            if is_pentagonal(p_i + p_j) and is_pentagonal(p_i - p_j):
                print(p_i - p_j, p_i, p_j, i, j)
                print("---Time spent:  %s seconds ---" % (time.time() - start_time))
                exit()

        i+=1

